package dev.panwar.projectpulse.models

import android.os.Parcel
import android.os.Parcelable

// Board is a Group where number of People are Contributing towards a Project
data class Board(
    val name:String="",
    val image:String="",
    val createdBy:String="",
    val assignedTo:ArrayList<String>
):Parcelable {
//    Below lines of code generated by Generate Parcelable code plugin
    constructor(parcel: Parcel) : this(
        parcel.readString()!!,
        parcel.readString()!!,
        parcel.readString()!!,
//       added by me...for Assigned to
        parcel.createStringArrayList()!!
    ) {
    }

    override fun writeToParcel(parcel: Parcel, flags: Int) = with(parcel) {
        parcel.writeString(name)
        parcel.writeString(image)
        parcel.writeString(createdBy)
        //       added by me...for Assigned to
        parcel.writeStringList(assignedTo)
    }

    override fun describeContents(): Int {
        return 0
    }

    companion object CREATOR : Parcelable.Creator<Board> {
        override fun createFromParcel(parcel: Parcel): Board {
            return Board(parcel)
        }

        override fun newArray(size: Int): Array<Board?> {
            return arrayOfNulls(size)
        }
    }
}
